//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastilleroApiIntegradora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Historial()
        {
            this.FichaTecnica = new HashSet<FichaTecnica>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<int> IdPadecimiento { get; set; }
        public Nullable<int> IdTratamiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FichaTecnica> FichaTecnica { get; set; }
        public virtual Padecimientos Padecimientos { get; set; }
        public virtual Tratamiento Tratamiento { get; set; }
    }
}
