//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastilleroApiIntegradora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<int> Edad { get; set; }
        public byte[] FotoPerfil { get; set; }
        public Nullable<int> IdDirecciones { get; set; }
        public Nullable<int> IdUsuarios { get; set; }
        public Nullable<int> IdFichaTecnica { get; set; }
    
        public virtual Direcciones Direcciones { get; set; }
        public virtual FichaTecnica FichaTecnica { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
