//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastilleroApiIntegradora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tratamiento()
        {
            this.Historial = new HashSet<Historial>();
        }
    
        public int Id { get; set; }
        public string TipoTratamiento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdMedicamento { get; set; }
        public Nullable<int> IdControl { get; set; }
    
        public virtual Control Control { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historial> Historial { get; set; }
        public virtual Medicamentos Medicamentos { get; set; }
    }
}
